### ISSUE TITLE
This block of code may produce NPE

### ISSUE THREAD

**Issue by howardchuc** [cgz104/MovieApp_Week1Intern#1]
https://github.com/cgz104/MovieApp_Week1Intern/blob/32554a9805f2453b14c21ebd81b7a76f0458ff71/Week1Intern_ver2/app/src/main/java/com/cuongz/week1intern_ver2/InsideItem.kt#L37

```
        var intent: Intent = getIntent()

        var objectMovie = intent.getParcelableExtra<Movie>("object")

        trailerPresenter.getMovieTrailer(objectMovie.getId()!!)
```

You should check null when getIntent 

https://stackoverflow.com/questions/9178253/how-to-handle-an-intent-which-does-not-have-data-at-first-call-of-an-activity

**Comment by cgz104** [comment]
Thanks for pointing out the issue
I have tried this, can you check
```
var intent: Intent = getIntent()

var objectMovie = intent.getParcelableExtra<Movie>("object")

val movieID = objectMovie.getId()
if(movieID != null){
     trailerPresenter.getMovieTrailer(movieID)
}
```

**Comment by howardchuc** [comment]
Look good :))
